openapi: 3.0.0
info:
  title: Calendar API
  description: API for managing calendar events
  version: 1.0.0
servers:
  - url: https://api.example.com/v1

paths:
  /events:
    get:
      summary: Retrieve all events
      operationId: api.events.get_events
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
    post:
      summary: Create a new event
      operationId: api.events.create_event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventInput"
      responses:
        "201":
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        "400":
          description: Invalid request payload

  /events/{eventId}:
    parameters:
      - name: eventId
        in: path
        description: ID of the event
        required: true
        schema:
          type: string
    get:
      summary: Get a specific event
      operationId: api.events.get_event
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        "404":
          description: Event not found
    put:
      summary: Update a specific event
      operationId: api.events.update_event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventInput"
      responses:
        "200":
          description: Event updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        "400":
          description: Invalid request payload
        "404":
          description: Event not found
    delete:
      summary: Delete a specific event
      operationId: api.events.delete_event
      responses:
        "204":
          description: Event deleted successfully
        "404":
          description: Event not found

components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the event
        title:
          type: string
          description: Title of the event
        description:
          type: string
          description: Description of the event
        startDateTime:
          type: string
          format: date-time
          description: Start date and time of the event
        endDateTime:
          type: string
          format: date-time
          description: End date and time of the event
        status:
          type: string
          description: Status of the event
      required:
        - id
        - title
        - startDateTime
        - endDateTime
    EventInput:
      type: object
      properties:
        title:
          type: string
          description: Title of the event
        description:
          type: string
          description: Description of the event
        startDateTime:
          type: string
          format: date-time
          description: Start date and time of the event
        endDateTime:
          type: string
          format: date-time
          description: End date and time of the event
      required:
        - title
        - startDateTime
        - endDateTime
