openapi: 3.0.0
info:
  title: Vacation Manager User API
  version: 1.0.0
paths:
  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid request body
        '500':
          description: Internal server error

  /users/{userId}:
    get:
      summary: Get user by ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user to retrieve
      responses:
        '200':
          description: User found
        '404':
          description: User not found
        '500':
          description: Internal server error

    put:
      summary: Update user by ID
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Invalid request body
        '404':
          description: User not found
        '500':
          description: Internal server error

components:
  schemas:
    UserInput:
      type: object
      properties:
        username:
          type: string
          description: The username of the user
        email:
          type: string
          format: email
          description: The email address of the user
        role:
          type: string
          enum: [user, admin]
          description: The role of the user
      required:
        - username
        - email
        - role
