baseURL = "http://example.com/"
languageCode = "en-us"
title = "Vacation Manager"


[params]
  description = "Vacation Manager"
  author = "Team White"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
